version: '2'
services:
  taxon-web:
    build: .
    environment:
      - DB_URL=taxon-mongo
    ports:
      - "127.0.0.1:8598:8598"
    depends_on:
      - taxon-mongo
    restart: always
  taxon-mongo:
    image: mongo:4.4.9
    ports:
      - "27017:27017"
    command: --quiet
    restart: always
