version: '2'
services:
  taxon-web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - taxon-mongo
  taxon-mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: --quiet
